import {setupTestDatabase} from './helpers/postgres.mjs';
await setupTestDatabase();
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawn} from 'node:child_process';
const temp=mkdtempSync(join(tmpdir(),'xin-agent-loop-test-'));process.env.XIN_DATA_DIR=temp;process.env.XIN_CODEX_BIN=join(temp,'codex-is-not-installed');
const m=await import('../lib/db.mjs');
const agent=await import('../lib/agent.mjs');
const spawned=[];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const alive=pid=>{try{process.kill(pid,0);return true;}catch(e){return e.code!=='ESRCH';}};
const settle=async id=>{for(let i=0;i<100&&['queued','running'].includes((await m.one('SELECT status FROM jobs WHERE id=?',id)).status);i++)await sleep(100);return (await m.one('SELECT * FROM jobs WHERE id=?',id));};
test('a missing Codex binary fails the job with the install message',async()=>{
 const id=(await agent.createJob('Review with no Codex'));spawned.push(id);(await agent.launchJob(id));
 const job=await settle(id);assert.equal(job.status,'failed');assert.match(job.error,/Codex is not installed/);
});
test('answers compose a follow-up prompt from the parent review and skip blank answers',async()=>{
 const parent=(await agent.createJob('Review the launch plan'));(await m.run("UPDATE jobs SET status='complete' WHERE id=?",parent));
 await assert.rejects(async ()=>(await agent.createJob('Follow-up','review',{answers:[{question:'Is the date fixed?',answer:'  '},{question:'Who owns the checklist?',answer:''}],parent_id:parent})),/Answer at least one question/);
 assert.equal((await m.one("SELECT count(*) AS n FROM jobs WHERE status='queued'")).n,0);
 const id=(await agent.createJob('Follow-up','review',{answers:[{question:'Is the date fixed?',answer:'Yes, 12 October.'},{question:'Who owns the checklist?',answer:''}],parent_id:parent}));
 const job=(await m.one('SELECT * FROM jobs WHERE id=?',id));
 assert.equal(job.prompt,`Follow-up to review ${parent}.\n\nMy answers to your questions:\n- Q: Is the date fixed?\n  A: Yes, 12 October.\n\nOriginal request: Review the launch plan\n\nContinue that review using these answers as verified facts from me. Re-check the sources, update the findings and proposals, and ask only new questions.`);
 assert.ok(!job.prompt.includes('Who owns the checklist?'));
 assert.equal((await m.one('SELECT body FROM sources WHERE id=?','manual:agent-request-'+id)).body,job.prompt);
 (await m.run("UPDATE jobs SET status='complete' WHERE id=?",id));
});
test('cancelJob records cancellation without killing an unrelated host PID and refuses finished reviews',async()=>{
 const id=(await agent.createJob('Long review'));
 const child=spawn(process.execPath,['-e','setInterval(()=>{},1000)'],{stdio:'ignore'});
 (await m.run("UPDATE jobs SET status='running',pid=? WHERE id=?",child.pid,id));
 assert.deepEqual((await agent.cancelJob(id)),{cancelled:true});
 const job=(await m.one('SELECT * FROM jobs WHERE id=?',id));
 assert.equal(job.status,'failed');assert.equal(job.error,'Review cancelled.');assert.equal(job.progress,'Cancelled');
 assert.equal(alive(child.pid),true);child.kill('SIGKILL');
 await assert.rejects(async ()=>(await agent.cancelJob(id)),/not running/);
 await assert.rejects(async ()=>(await agent.cancelJob('missing-job')),/not running/);
 await assert.rejects(async ()=>(await agent.cancelJob((await m.one("SELECT id FROM jobs WHERE status='complete'")).id)),/not running/);
});
test('cancelling a review drains a pending import review into a new job',async()=>{
 const id=(await agent.createJob('Review while imports arrive'));
 (await agent.queueImportReview());assert.ok((await m.getSetting('pending_import_review')));
 (await agent.cancelJob(id));
 const next=(await m.one("SELECT * FROM jobs WHERE kind='import_review' ORDER BY created_at DESC LIMIT 1"));
 assert.ok(next);spawned.push(next.id);assert.equal((await m.getSetting('pending_import_review')),null);
 assert.equal((await m.one('SELECT status FROM jobs WHERE id=?',id)).status,'failed');
 assert.equal((await settle(next.id)).status,'failed');
});
test.after(()=>rmSync(temp,{recursive:true,force:true}));
