CREATE TABLE IF NOT EXISTS sources(id TEXT PRIMARY KEY,provider TEXT NOT NULL,external_id TEXT NOT NULL,title TEXT NOT NULL,occurred_at TEXT NOT NULL DEFAULT '',body TEXT NOT NULL DEFAULT '',url TEXT NOT NULL DEFAULT '',coverage TEXT NOT NULL,content_hash TEXT NOT NULL,imported_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(provider,external_id));
CREATE TABLE IF NOT EXISTS source_versions(id TEXT PRIMARY KEY,source_id TEXT NOT NULL REFERENCES sources(id),content_hash TEXT NOT NULL,raw_json TEXT NOT NULL,fetched_at TEXT NOT NULL,UNIQUE(source_id,content_hash));
CREATE TABLE IF NOT EXISTS items(id TEXT PRIMARY KEY,title TEXT NOT NULL,kind TEXT NOT NULL DEFAULT 'action',status TEXT NOT NULL DEFAULT 'candidate',done_when TEXT NOT NULL DEFAULT '',next_action TEXT NOT NULL DEFAULT '',owner TEXT NOT NULL DEFAULT 'You',checkpoint TEXT NOT NULL DEFAULT '',hard_deadline TEXT NOT NULL DEFAULT '',original_checkpoint TEXT NOT NULL DEFAULT '',dependency TEXT NOT NULL DEFAULT '',evidence TEXT NOT NULL DEFAULT '',reason TEXT NOT NULL DEFAULT '',source_id TEXT REFERENCES sources(id),source_quote TEXT NOT NULL DEFAULT '',shared INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS events(id TEXT PRIMARY KEY,item_id TEXT NOT NULL REFERENCES items(id),action TEXT NOT NULL,before_json TEXT,after_json TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS jobs(id TEXT PRIMARY KEY,kind TEXT NOT NULL,status TEXT NOT NULL,prompt TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,result_json TEXT,error TEXT NOT NULL DEFAULT '',progress TEXT NOT NULL DEFAULT '',pid INTEGER);
CREATE TABLE IF NOT EXISTS proposals(id TEXT PRIMARY KEY,job_id TEXT NOT NULL REFERENCES jobs(id),fingerprint TEXT NOT NULL UNIQUE,status TEXT NOT NULL DEFAULT 'pending',payload TEXT NOT NULL,created_at TEXT NOT NULL,item_id TEXT REFERENCES items(id));
CREATE TABLE IF NOT EXISTS job_events(id BIGSERIAL PRIMARY KEY,job_id TEXT NOT NULL REFERENCES jobs(id),label TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sync_runs(id TEXT PRIMARY KEY,provider TEXT NOT NULL,started_at TEXT NOT NULL,finished_at TEXT,state TEXT NOT NULL,imported INTEGER NOT NULL DEFAULT 0,message TEXT NOT NULL DEFAULT '');
ALTER TABLE items ADD COLUMN IF NOT EXISTS last_action TEXT NOT NULL DEFAULT '';
ALTER TABLE items ADD COLUMN IF NOT EXISTS fallback TEXT NOT NULL DEFAULT '';
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS lease_owner TEXT NOT NULL DEFAULT '';
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS lease_until TIMESTAMPTZ;
ALTER TABLE sync_runs ADD COLUMN IF NOT EXISTS pid INTEGER;
ALTER TABLE sync_runs ADD COLUMN IF NOT EXISTS updated_at TEXT;
ALTER TABLE sync_runs ADD COLUMN IF NOT EXISTS changed INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sync_runs ADD COLUMN IF NOT EXISTS lease_owner TEXT NOT NULL DEFAULT '';
ALTER TABLE sync_runs ADD COLUMN IF NOT EXISTS lease_until TIMESTAMPTZ;
CREATE UNIQUE INDEX IF NOT EXISTS jobs_single_active ON jobs ((true)) WHERE status IN ('queued','running');
CREATE UNIQUE INDEX IF NOT EXISTS sync_single_active ON sync_runs ((true)) WHERE state IN ('queued','running');
CREATE INDEX IF NOT EXISTS source_search ON sources USING GIN (to_tsvector('simple', title || ' ' || body));
CREATE INDEX IF NOT EXISTS source_versions_latest ON source_versions(source_id,fetched_at DESC);
CREATE INDEX IF NOT EXISTS sources_chronology ON sources(occurred_at DESC,id);
CREATE INDEX IF NOT EXISTS events_item ON events(item_id,created_at DESC);
CREATE INDEX IF NOT EXISTS job_events_job ON job_events(job_id,id);
CREATE TABLE IF NOT EXISTS workspace_lock(id INTEGER PRIMARY KEY CHECK(id=1));
INSERT INTO workspace_lock VALUES(1) ON CONFLICT DO NOTHING;
CREATE SCHEMA IF NOT EXISTS focus_auth;
REVOKE ALL ON SCHEMA focus_auth FROM PUBLIC;
CREATE TABLE IF NOT EXISTS focus_auth.owner(id INTEGER PRIMARY KEY CHECK(id=1),sub TEXT NOT NULL,email TEXT NOT NULL,name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS focus_auth.sessions(token_hash TEXT PRIMARY KEY,sub TEXT NOT NULL,created_at BIGINT NOT NULL,expires_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS focus_auth.oauth_attempts(state_hash TEXT PRIMARY KEY,browser_hash TEXT NOT NULL,verifier TEXT NOT NULL,nonce TEXT NOT NULL,client_id TEXT NOT NULL,expires_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS focus_auth.auth_events(id BIGSERIAL PRIMARY KEY,created_at TEXT NOT NULL,stage TEXT NOT NULL,outcome TEXT NOT NULL,code TEXT NOT NULL,http_status INTEGER,provider_reason TEXT);
REVOKE ALL ON ALL TABLES IN SCHEMA focus_auth FROM PUBLIC;
